routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);
Route::get('logout', 'HomeController@logout')->name('logout');

Route::group(['middleware' => 'verified'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('people', 'MemberController');
    Route::resource('users', 'UserController');
    Route::resource('bureau', 'TeamController');
    Route::resource('departments', 'RoleController')->except(['show']);
    Route::resource('reports', 'ReportController');
    Route::resource('meetings', 'MeetingController')->except(['show']);
    Route::resource('events', 'EventController')->except(['show']);
    Route::resource('finances', 'FinanceController')->only(['index', 'edit']);
    Route::resource('contributions', 'ContributionController')->only(['index', 'edit', 'store', 'destroy']);
    Route::resource('incomes', 'IncomeController')->only(['store', 'destroy']);
    Route::resource('expenses', 'ExpenseController')->only(['store', 'destroy']);
});

resources/views/partials/error.blade.php
@if($errors->any())
    <div class="alert alert-warning message">

            @foreach($errors->all() as $error)
                {{$error}}<br>
            @endforeach

    </div>
@elseif (session('success'))
    <div class="alert alert-info text-center message">
        <strong>{{ session('success') }}</strong>
    </div>
    <script>
        window.setTimeout(function () {
            $(".message").fadeTo(700, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 5000);
    </script>
@elseif(session('warning'))
    <div class="alert alert-warning text-center message">
        <strong>{{ session('warning') }}</strong>
    </div>
    <script>
        window.setTimeout(function () {
            $(".message").fadeTo(700, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 5000);
    </script>
@elseif(session('status'))
    <div class="alert alert-warning text-center message">
        <strong>{{ session('status') }}</strong>
    </div>
@endif

resources/views/partials/formMessage.blade.php
@if(!$errors->any())
    <div class="col-lg-12 alert alert-warning text-center display">
        <h4>Fields in orange must not be empty!!!</h4>
    </div>
    <script>
        window.setTimeout(function () {
            $(".display").fadeTo(700, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 4000);
    </script>
@endif

resources/views/partials/nav.blade.php
<div class="topbar-left visible-lg" style="background-color: #c7c7c7">
    <div class="text-center">
        <a href="{{ route('people.index') }}" class="logo">
            <span style="color: #0cb800">AD</span><span style="color: #f2f000">EG</span><span style="color: blue">AC</span>
        </a>
        <a href="index.html" class="logo-sm">
            <small style="color: #0cb800">AD</small><small style="color: #f2f000">EG</small><small style="color: blue">AC</small>
        </a>
    </div>
</div>
<div class="navbar navbar-default" role="navigation">
    <div class="container" style="padding: 0">
        <div class="">
            <div class="pull-left">
                <button type="button" class="button-menu-mobile open-left waves-effect waves-light"><i
                            class="ion-navicon"></i>
                </button>
                <span class="clearfix"></span></div>
            <ul class="nav navbar-nav navbar-right pull-right">
                <li class="dropdown">
                    <a href="" class="dropdown-toggle profile waves-effect waves-light"
                       data-toggle="dropdown" aria-expanded="true">
                        {{--{{ dd(\Illuminate\Support\Facades\Auth::user()->member()->latest()->first()) }}--}}
                        @if(\Illuminate\Support\Facades\Auth::user()->member()->latest()->first() == null )
                            <img src="{{ Avatar::create(\Illuminate\Support\Facades\Auth::user()->email)->setDimension(200)->setFontSize(92)->toBase64()}}"
                                 alt="user-img" class="img-circle">
                        @else
                            <img src="{{\Illuminate\Support\Facades\Auth::user()->member()->latest()->first()->picture}}" alt="" class="img-circle">
                        @endif
                        <span class="profile-username"> {{\Illuminate\Support\Facades\Auth::user()->member()->first() == null ? \Illuminate\Support\Facades\Auth::user()->email : \Illuminate\Support\Facades\Auth::user()->member()->first()->first_name }} <br/>
                            <small>
                               {{ \Illuminate\Support\Facades\Auth::user()->roles()->first()->display_name }}
                            </small>
                        </span> </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('logout')}}"
                               onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

resources/views/partials/sidebar.blade.php
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <div class="user-details">
            <div class="text-center">
                @if(\Illuminate\Support\Facades\Auth::user()->member()->latest()->first() == null )
                    <img src="{{ Avatar::create(\Illuminate\Support\Facades\Auth::user()->email)->setDimension(200)->setFontSize(92)->toBase64()}}"
                         alt="user-img" class="img-circle">
                @else
                    <img src="{{ \Illuminate\Support\Facades\Auth::user()->member()->latest()->first()->picture }}"
                         alt="" class="img-circle">
                @endif
            </div>
            <div class="user-info">
                <div class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                         aria-expanded="false"> {{ \Illuminate\Support\Facades\Auth::user()->roles()->first()->display_name }}</a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"> Logout
                            </a>
                        </li>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </div>
                <p class="text-white m-0"><i class="fa fa-dot-circle-o text-success"></i> Online</p></div>
        </div>
        <div id="sidebar-menu">
            <ul>
                @permission('browse-people|edit-people|add-people|browse-contributions|edit-contributions')
                {{--Members--}}
                <li class="">
                    <a href="{{ route('people.index') }}"
                       class="waves-effect {{ Nav::isResource('people') }}{{ Nav::isResource('contributions') }}">
                        <i class="fa fa-4x fa-group" aria-hidden="true"></i>
                        <span> Community</span>
                    </a>
                </li>
                @endpermission
                @permission('browse-events|edit-events|add-events')
                {{--Events--}}
                <li class="">
                    <a href="{{route('events.index')}}"
                       class="waves-effect {{ Nav::isResource('events') }}{{ Nav::isResource('finances') }}"><i
                            class="fa fa-calendar"></i>
                        <span> Calendar </span></a>
                </li>
                @endpermission
                @permission('browse-reports|edit-reports|add-reports')
                {{--Reports--}}
                <li><a class="waves-effect {{ Nav::isResource('reports') }}" href="{{ route('reports.index') }}">
                        <i class="fa fa-files-o"></i> Reports</a>
                </li>
                @endpermission
                @permission('browse-bureaus|edit-bureaus|add-bureaus')
                {{--Bureau--}}
                <li><a class="waves-effect {{ Nav::isResource('bureau') }}" href="{{ route('bureau.index') }}">
                        <i class="fa fa-users"></i> Bureau</a>
                </li>
                @endpermission
                @permission('browse-departments|edit-departments|add-departments')
                {{--Departments--}}
                <li><a class="waves-effect {{ Nav::isResource('departments') }}"
                       href="{{ route('departments.index') }}">
                        <i class="fa fa-briefcase"></i> Departments</a>
                </li>
                @endpermission
                @permission('browse-users|edit-users|add-users')
                {{--Users--}}
                <li><a class="waves-effect {{ Nav::isResource('users') }}" href="{{ route('users.index') }}">
                        <i class="fa fa-user-secret"></i> Users</a>
                </li>
                @endpermission
                @permission('browse-meetings|edit-meetings|add-meetings')
                {{--Meetings--}}
                <li><a class="waves-effect {{ Nav::isResource('meetings') }}" href="{{ route('meetings.index') }}">
                        <i class="fa fa-calendar fa-plus"></i> Meetings</a>
                </li>
                @endpermission
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
</div>