routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);
Route::get('logout', 'HomeController@logout')->name('logout');

Route::group(['middleware' => 'verified'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('people', 'MemberController');
    Route::resource('users', 'UserController');
    Route::resource('bureau', 'TeamController');
    Route::resource('departments', 'RoleController')->except(['show']);
    Route::resource('reports', 'ReportController');
    Route::resource('meetings', 'MeetingController')->except(['show']);
    Route::resource('events', 'EventController')->except(['show']);
    Route::resource('finances', 'FinanceController')->only(['index', 'edit']);
    Route::resource('contributions', 'ContributionController')->only(['index', 'edit', 'store', 'destroy']);
    Route::resource('incomes', 'IncomeController')->only(['store', 'destroy']);
    Route::resource('expenses', 'ExpenseController')->only(['store', 'destroy']);
});

resources/views/bureau/add.blade.php
@extends('layouts.master')

@section('title')
    Add Bureau
@endsection

@section('pageScript')
    <link href="{{asset('/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}" rel="stylesheet">
@endsection


@section('content')
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-body">
                            <h3 class="page-header text-center">New Bureau</h3>
                            @include('partials.error')
                            @include('partials.formMessage')

                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <form class="form-horizontal" role="form" method="POST" action="{{ route('bureau.store') }}"
                                          enctype="multipart/form-data">

                                        {{csrf_field()}}

                                        <div class="container">
                                            <div class="form-group{{$errors->has('name') ? ' has-error' : ' has-warning'}}">
                                                <label for="">Bureau Name</label>
                                                <input type="text" class="form-control" name="name"
                                                       placeholder="Bureau Name" autocomplete="off"
                                                       value="{{old('name')}}">
                                            </div>

                                            <div
                                                class="form-group{{$errors->has('first_name') ? ' has-error' : ''}}">
                                                <label for="">Description</label>
                                                <textarea name="description" id="description" class="form-control"
                                                          rows="3"
                                                          placeholder="Description">{{ old('description') }}</textarea>
                                            </div>

                                            <div class="row form-group">
                                                <div class="col-md-6 ">
                                                    <div class="form-group">
                                                        <label for="">Starting Date</label>
                                                        <div
                                                            class=" input-group{{$errors->has('start_date') ? ' has-error' : ' has-warning'}}">

                                                            <input type="text" class="form-control date" name="start_date"
                                                                   placeholder="Starting Date" autocomplete="off"
                                                                   value="{{old('start_date')}}"
                                                                   readonly>
                                                            <span class="input-group-addon bg-custom b-0"><i
                                                                    class="mdi mdi-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6 col-xs-12">
                                                    <label for="">Ending Date</label>
                                                    <div
                                                        class="input-group{{$errors->has('end_date') ? ' has-error' : ''}}">

                                                        <input type="text" class="form-control date" name="end_date"
                                                               placeholder="Ending Date" autocomplete="off"
                                                               value="{{old('end_date')}}"
                                                               readonly>
                                                        <span class="input-group-addon bg-custom b-0"><i
                                                                class="mdi mdi-calendar"></i></span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class=" text-right">
                                                    <button type="submit" class="btn btn-dark "><i
                                                            class="fa fa-plus-circle"></i> Add Bureau
                                                    </button>
                                                    <a href="{{ route('bureau.index') }}" class="btn btn-default"><i
                                                            class="fa fa-reply"></i> Back</a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('script')
    <script src="{{asset('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>
    <script>
        datePicker();
    </script>
@endsection

resources/views/bureau/edit.blade.php
@extends('layouts.master')

@section('title')
    Edit Bureau
@endsection

@section('pageScript')
    <link href="{{asset('/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}" rel="stylesheet">
@endsection


@section('content')
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-body">
                            <h3 class="page-header text-center">Edit Bureau - {{ $bureau->display_name }}</h3>
                            @include('partials.error')

                            @include('partials.formMessage')


                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <form class="form-horizontal" role="form" method="POST"
                                          action="{{ route('bureau.update', ['bureau' => $bureau]) }}"
                                          enctype="multipart/form-data">

                                        {{csrf_field()}}
                                        {{ method_field("PATCH") }}

                                        <div class="container">
                                            <div
                                                class="form-group{{$errors->has('name') ? ' has-error' : ' has-warning'}}">
                                                <label for="">Bureau Name</label>
                                                <input type="text" class="form-control" name="name"
                                                       placeholder="Bureau Name" autocomplete="off"
                                                       value="{{old('name') ? old('name') : $bureau->display_name}}">
                                            </div>

                                            <div
                                                class="form-group{{$errors->has('first_name') ? ' has-error' : ''}}">
                                                <label for="">Description</label>
                                                <textarea name="description" id="description" class="form-control"
                                                          rows="3"
                                                          placeholder="Description">{{ old('description') ? old('description') : $bureau->description }}</textarea>
                                            </div>

                                            <div class="row form-group">
                                                <div class="col-md-6 ">
                                                    <div class="form-group">
                                                        <label for="">Starting Date</label>
                                                        <div
                                                            class=" input-group{{$errors->has('start_date') ? ' has-error' : ' has-warning'}}">

                                                            <input type="text" class="form-control date"
                                                                   name="start_date"
                                                                   placeholder="Starting Date" autocomplete="off"
                                                                   value="{{old('start_date') ? old('start_date') : \Carbon\Carbon::parse($bureau->start_date)->toDateString()}}"
                                                                   readonly>
                                                            <span class="input-group-addon bg-custom b-0"><i
                                                                    class="mdi mdi-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6 col-xs-12">
                                                    <label for="">Ending Date</label>
                                                    <div
                                                        class="input-group{{$errors->has('end_date') ? ' has-error' : ''}}">

                                                        <input type="text" class="form-control date" name="end_date"
                                                               placeholder="Ending Date" autocomplete="off"
                                                               value="{{old('end_date') ? old('end_date') : $bureau->end_date == null ? \Carbon\Carbon::parse($bureau->start_date)->addMonths(12)->toDateString() : \Carbon\Carbon::parse($bureau->start_date)->toDateString() }}"
                                                               readonly>
                                                        <span class="input-group-addon bg-custom b-0"><i
                                                                class="mdi mdi-calendar"></i></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="col-md-12 col-xs-12">
                                            <div class="form-group">
                                                <div class=" text-right">
                                                    <button type="submit" class="btn btn-dark "><i
                                                            class="fa fa-save"></i> Save
                                                    </button>
                                                    <a href="{{ route('bureau.index') }}" class="btn btn-default"><i
                                                            class="fa fa-reply"></i> Back</a>
                                                </div>
                                            </div>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('script')
    <script src="{{asset('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>
    <script>
        datePicker();
    </script>
@endsection

resources/views/bureau/index.blade.php
@extends('layouts.master')

@section('title')
    Bureaus
@endsection

@section('pageScript')
    <link href="{{asset('/plugins/datatables/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/buttons.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/responsive.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
@endsection


@section('content')
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="form-group text-right">
                @permission('add-bureaus')
                <a href="{{route('bureau.create')}}" class="btn btn-md btn-dark waves-light waves-effect"><i
                        class="fa fa-plus-circle" title="Add Member"></i> Add Bureau
                </a>
                @endpermission
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            @include('partials.error')


                            <table id="bureau_table" class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Bureau's Name</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th># Members</th>
                                    @permission('read-bureaus|edit-bureaus|delete-bureaus')
                                    <th></th>
                                    @endpermission
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($bureaus as $index => $bureau)

                                    <tr>
                                        <td>{{ $index+1 }}</td>
                                        <td>{{$bureau->display_name}}</td>
                                        <td>{{\Carbon\Carbon::parse($bureau->start_date)->toDateString()}}</td>
                                        <td>{{ $bureau->end_date == null ? 'Mandat will end on '. \Carbon\Carbon::parse($bureau->start_date)->addMonths(12)->toDateString() : \Carbon\Carbon::parse($bureau->start_date)->toDateString() }}</td>
                                        <td>{{ $bureau->users()->count() }}</td>
                                        @permission('read-bureaus|edit-bureaus|delete-bureaus')
                                        <td class="float-right">
                                            @permission('read-bureaus')
                                            @if($bureau->users()->count() !== 0)
                                            <a href="{{ route('bureau.show', ['bureau' => $bureau]) }}"
                                               class="btn btn-xs btn-info waves-effect">
                                                <i class="fa fa-eye" title="Edit Bureau"></i>
                                            </a>
                                            @endif
                                            @endpermission
                                            @permission('edit-bureaus')
                                            <a href="{{ route('bureau.edit', ['bureau' => $bureau]) }}"
                                               class="btn btn-xs btn-success waves-effect"><i
                                                    class="fa fa-pencil"></i>
                                            </a>
                                            @endpermission
                                            @permission('|delete-bureaus')
                                            <a href="{{ route('bureau.destroy', ['bureau' => $bureau]) }}"
                                               onclick="deleting('#delete-bureau{{$bureau->id}}', 'Bureau')"
                                               class="btn btn-xs btn-danger waves-effect"><i
                                                    class="fa fa-trash" title="Delete Member"></i>
                                            </a>
                                            <form class="hidden"
                                                  action="{{ route('bureau.destroy', ['bureau' => $bureau]) }}"
                                                  method="POST" id="delete-bureau{{$bureau->id}}">
                                                {{ @csrf_field() }}
                                                {{ method_field("DELETE") }}
                                            </form>
                                            @endpermission
                                        </td>
                                        @endpermission
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{asset('/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/responsive.bootstrap.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('#bureau_table').DataTable({
                stateSave: true,
                "ordering": true,
                language: {
                    searchPlaceholder: "Searching...."
                },
                dom: 'frtp',
                responsive: true
            });
        });
    </script>
@endsection

resources/views/bureau/view.blade.php
@extends('layouts.master')

@section('title')
    View Bureau
@endsection


@section('content')

    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="panel-heading">
                                <h3 class="page-header text-center mt-0">{{ $bureau->display_name }} - Bureau
                                    Information
                                    <a href="{{ route('bureau.index') }}" class="btn btn-default pull-right"> <i
                                            class="fa fa-reply"></i> Bureaus</a></h3>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        @foreach($bureau->users()->get() as $user)
                                        <div class="col-md-4">
                                            <div class="panel">
                                                <div class="panel-body">
                                                    <div class="row">
                                                        <div class="col-md-4">
                                                            <img
                                                                src="{{ Avatar::create($user->fullName())->setDimension(75)->setFontSize(35)->toBase64()}}"
                                                                class="img img-circle"
                                                                alt="">
                                                        </div>
                                                        <div class="col-md-8">
                                                            <div class="">
                                                                <label for="">Name:</label>
                                                                <small>{{ $user->fullName() }}</small>
                                                            </div>
                                                            <div class="">
                                                                <label for="">Role:</label>
                                                                <small>{{ $user->roles()->first()->display_name }}</small>
                                                            </div>
                                                            <a href="{{ route('people.show', ['person' => $user->member()->first()]) }}">View Information</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script>
        $(document).ready(function () {
            $("span:contains('Administration')").parent('a').addClass('active').click().addClass('subdrop');
        });
    </script>
@endsection