routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);
Route::get('logout', 'HomeController@logout')->name('logout');

Route::group(['middleware' => 'verified'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('people', 'MemberController');
    Route::resource('users', 'UserController');
    Route::resource('bureau', 'TeamController');
    Route::resource('departments', 'RoleController')->except(['show']);
    Route::resource('reports', 'ReportController');
    Route::resource('meetings', 'MeetingController')->except(['show']);
    Route::resource('events', 'EventController')->except(['show']);
    Route::resource('finances', 'FinanceController')->only(['index', 'edit']);
    Route::resource('contributions', 'ContributionController')->only(['index', 'edit', 'store', 'destroy']);
    Route::resource('incomes', 'IncomeController')->only(['store', 'destroy']);
    Route::resource('expenses', 'ExpenseController')->only(['store', 'destroy']);
});

resources/views/department/add.blade.php
@extends('layouts.master')

@section('title')
    Add Department
@endsection

@section('pageScript')
    <link rel="stylesheet" href="{{asset('/plugins/bootstrap-toggle/css/bootstrap-toggle.min.css')}}">
@endsection

@section('content')
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel">
                        <div class="panel-body">
                            <h3 class="page-header text-center">Department Information</h3>
                            @include('partials.error')

                            @include('partials.formMessage')


                            <form class="form-horizontal" role="form" method="POST"
                                  action="{{ route('departments.store') }}">

                                {{csrf_field()}}

                                <div class="row">
                                    <div class="col-lg-offset-1 col-lg-10 col-xs-12">

                                        <div class="form-group{{$errors->has('name') ? ' has-error' : ' has-warning'}}">
                                            <label for="">Department Name</label>
                                            <input type="text" class="form-control" name="name"
                                                   placeholder="Department Name" autocomplete="off"
                                                   value="{{old('name')}}">
                                        </div>

                                        <div class="form-group{{$errors->has('description') ? ' has-error' : ''}}">
                                            <label for="">Description</label>
                                            <textarea name="description" id="description"
                                                      placeholder="Description" class="form-control"
                                                      rows="3">{{ old('description') }}</textarea>
                                        </div>

                                        @foreach($permissionCategories as $permissionCategory)

                                            <div class="form-group row">
                                                <div class="col-md-12">
                                                    <h4 class="form-check-label">{{ucfirst(str_replace('_', ' ', $permissionCategory))}}</h4>
                                                </div>
                                                <div class="col-md-12 row">
                                                    @foreach($permissions as $count => $permission)
                                                        @if(strpos($permission->name, $permissionCategory) !== false)
                                                            <div class="col-md-2">
                                                                <div class="form-group">
                                                                    <label class="checkbox-inline ">
                                                                        <input type="checkbox"
                                                                               data-toggle="toggle"
                                                                               data-onstyle="success"
                                                                               data-offstyle="danger"
                                                                               data-size="small"
                                                                               name="permissions[]"
                                                                               value="{{$permission->id}}"
                                                                        >{{ucfirst($permission->display_name)}}
                                                                    </label>
                                                                </div>

                                                            </div>
                                                        @endif
                                                    @endforeach
                                                </div>

                                            </div>
                                        @endforeach

                                        <div class="form-group">
                                            <div class=" text-right">
                                                <button type="submit" class="btn btn-dark "><i
                                                        class="fa fa-plus-circle"></i> Add
                                                </button>
                                                <a href="{{ route('departments.index') }}" class="btn btn-default"><i
                                                        class="fa fa-reply"></i> Back</a>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{asset('/plugins/bootstrap-toggle/js/bootstrap-toggle.min.js')}}"></script>
@endsection

resources/views/department/edit.blade.php
@extends('layouts.master')

@section('title')
    Edit Department
@endsection

@section('pageScript')
    <link rel="stylesheet" href="{{asset('/plugins/bootstrap-toggle/css/bootstrap-toggle.min.css')}}">
@endsection

@section('content')
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel">
                        <div class="panel-body">
                            @include('partials.error')

                            @include('partials.formMessage')

                            <h3 class="page-header text-center">Department Information</h3>

                            <form class="form-horizontal" role="form" method="POST"
                                  action="{{ route('departments.update', ['department' => $department]) }}">

                                {{csrf_field()}}
                                {{ method_field('patch') }}

                                <div class="row">
                                    <div class="col-lg-offset-1 col-lg-10 col-xs-12">

                                        <div class="form-group{{$errors->has('name') ? ' has-error' : ' has-warning'}}">
                                            <label for="">Department Name</label>
                                            <input type="text" class="form-control" name="name"
                                                   placeholder="Department Name" autocomplete="off"
                                                   value="{{ old('name') ? old('name') : $department->display_name}}">
                                        </div>

                                        <div class="form-group{{$errors->has('description') ? ' has-error' : ''}}">
                                            <label for="description">Description</label>
                                            <textarea name="description" id="description" class="form-control"
                                                      rows="3">{{ old('description') ? old('description') : $department->description }}</textarea>
                                        </div>

                                        <h4>Permissions</h4>
                                        <hr>
                                        @foreach($permissionCategories as $permissionCategory)

                                            <div class="form-group row">
                                                <div class="col-md-12">
                                                    <h4 class="form-check-label">{{ucfirst(str_replace('_', ' ', $permissionCategory))}}</h4>
                                                </div>
                                                <div class="col-md-12 row">
                                                    @foreach($permissions as $count => $permission)
                                                        @if(strpos($permission->name, $permissionCategory) !== false)
                                                            <div class="col-md-2">
                                                                <div class="form-group">
                                                                    <label class="checkbox-inline ">
                                                                        <input type="checkbox"
                                                                               data-toggle="toggle"
                                                                               data-onstyle="success"
                                                                               data-offstyle="danger"
                                                                               data-size="small"
                                                                               name="permissions[]"
                                                                               value="{{$permission->id}}"
                                                                            {{ old('permissions[]') ? $department->rolePermission($permission->id, old('permissions[]'))? 'checked' : '' : $department->rolePermission($permission->id) ? 'checked' : '' }}>{{ucfirst($permission->display_name)}}
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        @endif
                                                    @endforeach
                                                </div>
                                            </div>
                                        @endforeach

                                        <div class="form-group">
                                            <div class=" text-right">
                                                <button type="submit" class="btn btn-dark "><i class="fa fa-save"></i>
                                                    Save
                                                </button>
                                                <a href="{{ route('departments.index') }}" class="btn btn-default"><i
                                                            class="fa fa-reply"></i> Back</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('script')
    <script src="{{asset('/plugins/bootstrap-toggle/js/bootstrap-toggle.min.js')}}"></script>
@endsection

resources/views/department/index.blade.php
@extends('layouts.master')

@section('title')
    Departments
@endsection

@section('pageScript')
    <link href="{{asset('/plugins/datatables/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/buttons.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/responsive.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
@endsection


@section('content')
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group text-right">
                        @permission('add-departments')
                        <a href="{{route('departments.create')}}" class="btn btn-md btn-dark waves-light waves-effect"><i
                                    class="fa fa-plus-circle" title="Add Department"></i> Add Department
                        </a>
                        @endpermission
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            @include('partials.error')

                            <table id="department_table" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Last Update</th>
                                    @permission('edit-departments|delete-departments')
                                    <th>Actions</th>
                                    @endpermission
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($departments as $index => $department)
                                    <tr>
                                        <td>{{ $index+1 }}</td>
                                        <td>{{$department->display_name}}</td>
                                        <td>{{ \Carbon\Carbon::parse($department->updated_at)->toDayDateTimeString() }}</td>
                                        @permission('edit-departments|delete-departments')
                                        <td class="float-right">
                                            @permission('edit-departments')
                                            <a href="{{ route('departments.edit', ['department' => $department]) }}" class="btn btn-xs btn-success waves-effect"><i
                                                        class="fa fa-pencil"></i>
                                            </a>
                                            @endpermission
                                            @permission('delete-departments')
                                            <a href="{{ route('departments.destroy', ['department' => $department]) }}" onclick="deleting('#delete-department{{$department->id}}', 'Department')"
                                               class="btn btn-xs btn-danger waves-effect"><i
                                                        class="fa fa-trash"></i>
                                            </a>
                                            <form class="hidden" action="{{ route('departments.destroy', ['department' => $department]) }}" method="POST" id="delete-department{{$department->id}}">
                                                {{ @csrf_field() }}
                                                {{ method_field("DELETE") }}
                                            </form>
                                            @endpermission
                                        </td>
                                        @endpermission
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{asset('/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/responsive.bootstrap.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('#department_table').DataTable({
                stateSave: true,
                "ordering": true,
                language: {
                    searchPlaceholder: "Searching...."
                },
                dom: 'frtp',
                responsive: true
            });
        });
    </script>
@endsection