routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);
Route::get('logout', 'HomeController@logout')->name('logout');

Route::group(['middleware' => 'verified'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('people', 'MemberController');
    Route::resource('users', 'UserController');
    Route::resource('bureau', 'TeamController');
    Route::resource('departments', 'RoleController')->except(['show']);
    Route::resource('reports', 'ReportController');
    Route::resource('meetings', 'MeetingController')->except(['show']);
    Route::resource('events', 'EventController')->except(['show']);
    Route::resource('finances', 'FinanceController')->only(['index', 'edit']);
    Route::resource('contributions', 'ContributionController')->only(['index', 'edit', 'store', 'destroy']);
    Route::resource('incomes', 'IncomeController')->only(['store', 'destroy']);
    Route::resource('expenses', 'ExpenseController')->only(['store', 'destroy']);
});

resources/views/people/index.blade.php
@extends('layouts.master')

@section('title')
    Members
@endsection

@section('pageScript')
    <link href="{{asset('/plugins/datatables/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/responsive.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
@endsection


@section('content')

    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-xs-4">
                    <div class="panel text-center">
                        <div class="panel-heading visible-lg"><h4 class="panel-title text-muted font-light">Total
                                Subscription</h4></div>
                        <div class="panel-body p-t-10">
                            <h1 class="m-t-0 m-b-0"><i
                                        class="mdi mdi-account-multiple text-danger m-r-10"></i><b>{{ \App\Member::countingMembers() }}</b>
                            </h1>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-xs-4">
                    <div class="panel text-center">
                        <div class="panel-heading visible-lg"><h4 class="panel-title text-muted font-light">Total Male
                                Members</h4>
                        </div>
                        <div class="panel-body p-t-10">

                            <h1 class="m-t-0 m-b-0"><i class="mdi mdi-gender-male text-primary m-r-0"></i><b>
                                    {{ \App\Member::countingMembers('Male')  }}</b>
                            </h1>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-xs-4">
                    <div class="panel text-center">
                        <div class="panel-heading visible-lg"><h4 class="panel-title text-muted font-light">Total Female
                                Members</h4></div>
                        <div class="panel-body p-t-10">
                            <h1 class="m-t-0 m-b-0"><i
                                        class="mdi mdi-gender-female  text-success m-r-0"></i><b>{{\App\Member::countingMembers('Female') }}</b>
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            @include('partials.error')
                            <div class="form-group text-right">
                                @permission('browse-contributions')
                                <a href="{{route('contributions.index')}}"
                                   class="btn btn-md btn-dark waves-light waves-effect" style="margin-bottom: 10px;">
                                    <i
                                            class="fa fa-plus"></i> Member's Contribution
                                </a>
                                @endpermission
                                @permission('add-people')
                                <a href="{{route('people.create')}}"
                                   class="btn btn-md btn-dark waves-light waves-effect" style="margin-bottom: 10px;"><i
                                            class="fa fa-plus-circle" title="Add Member"></i> Add Member
                                </a>
                                @endpermission
                            </div>

                            <table id="person_table" class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Full Name</th>
                                    <th>Passport No</th>
                                    <th>Contact No</th>
                                    <th>Email</th>
                                    @permission('read-people|edit-people|delete-people')
                                    <th style="width: 7%">Actions</th>
                                    @endpermission
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($people as $index => $person)
                                    <tr>
                                        <td style="width: 2%">{{ $index +1 }}</td>
                                        <td>{{$person->first_name}} <b>{{$person->last_name}}</b></td>
                                        <td>{{strtoupper($person->passport_number)}}</td>
                                        <td>{{$person->cell_number}}</td>
                                        <td>{{$person->email}}</td>
                                        @permission('read-people|edit-people|delete-people')
                                        <td class="float-right">
                                            @permission('read-people')
                                            <a href="{{ route('people.show', ['person' => $person]) }}"
                                               class="btn btn-xs btn-info waves-effect">
                                                <i class="fa fa-eye" title="Edit Member"></i>
                                            </a>
                                            @endpermission
                                            @permission('edit-people')
                                            <a href="{{ route('people.edit', ['person' => $person]) }}"
                                               class="btn btn-xs btn-success waves-effect"><i
                                                        class="fa fa-pencil"></i>
                                            </a>
                                            @endpermission
                                            @permission('delete-people')
                                            <a href="{{ route('people.destroy', ['person' => $person]) }}"
                                               onclick="deleting('#delete-person{{$person->id}}', 'Meeting')"
                                               class="btn btn-xs btn-danger waves-effect"><i
                                                        class="fa fa-trash" title="Delete Member"></i>
                                            </a>
                                            <form class="hidden"
                                                  action="{{ route('people.destroy', ['person' => $person]) }}"
                                                  method="POST" id="delete-person{{$person->id}}">
                                                {{ @csrf_field() }}
                                                {{ method_field("DELETE") }}
                                            </form>
                                            @endpermission
                                        </td>
                                        @endpermission
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{asset('/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/responsive.bootstrap.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                stateSave: true,
                "ordering": false,
                language: {
                    searchPlaceholder: "Searching...."
                },
                dom: 'frtp',
                responsive: true
            });
        });
    </script>
@endsection

resources/views/people/view.blade.php
@extends('layouts.master')

@section('title')
    View Member's Profile
@endsection

@section('pageScript')
    <link href="{{asset('/plugins/datatables/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/buttons.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/responsive.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('/plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
@endsection

@section('content')

    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel">
                        <div class="panel-body">
                            @include('partials.error')
                            <div class="text-right">
                                @permission('browse-people')
                                <a href="{{ route('people.index') }}"
                                   class="btn btn-sm btn-dark waves-light waves-effect"><i class="fa fa-reply"></i>
                                    &nbsp;Back &nbsp;</a>
                                @endpermission
                                @permission('edit-people')
                                <a href="{{ route('people.edit', ['person' => $person]) }}"
                                   class="btn btn-sm btn-success waves-light waves-effect"><i class="fa fa-pencil"></i>
                                    &nbsp;Edit &nbsp;</a>
                                @endpermission
                                @permission('delete-people')
                                <a href="{{ route('people.destroy', ['person' => $person]) }}" onclick="deleting('#delete-person{{$person->id}}', 'Meeting')"
                                   class="btn btn-sm btn-danger waves-effect"><i
                                        class="fa fa-trash" title="Delete Member"></i> Delete
                                </a>
                                <form class="hidden" action="{{ route('people.destroy', ['person' => $person]) }}" method="POST" id="delete-person{{$person->id}}">
                                    {{ @csrf_field() }}
                                    {{ method_field("DELETE") }}
                                </form>
                                @endpermission
                            </div>

                            <div class="panel-heading">
                                <h3 class="page-header text-center">Information</h3>
                            </div>

                            <div class="row">
                                <div class="col-lg-2 col-xs-12" style="margin-bottom: 10px">
                                    @if($person->picture == null)
                                        <img src="{{asset('/images/users/avatar-1.jpg')}}"
                                         style="  border: solid;display: block; margin: auto; width: 60%; padding: 10px;" alt="user img">
                                    @else
                                        <img src="{{ $person->picture }}" alt="{{$person->last_name}}"
                                             style="  border: solid;display: block; margin: auto; width: 60%; padding: 10px;">
                                    @endif
                                </div>
                                <div class="col-lg-9">
                                    <div class="col-lg-6 col-xs-12">
                                        <div class="form-group ">
                                            <label for="last_name">Last Name</label>
                                            <input type="text" class="form-control" value="{{$person->last_name}}" readonly id="last_name">
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="">First Name</label>
                                            <input type="text" class="form-control" value="{{$person->first_name}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-3 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Date of Birth</label>
                                            <input type="text" class="form-control" value="{{$person->dob}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-3 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Place of Birth</label>
                                            <input type="text" class="form-control" value="{{$person->pob}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-3 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Gender</label>
                                            <input type="text" class="form-control" value="{{$person->gender}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-3 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Passport number</label>
                                            <input type="text" class="form-control" value="{{$person->passport_number}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-3 col-xs-12">
                                        <div class="form-group">
                                            <label for="">Occupation</label>
                                            <input type="text" class="form-control" value="{{$person->occupation_title}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-xs-12">
                                        <div class="form-group">
                                            <label for="">Course or Career</label>
                                            <input type="text" class="form-control" value="{{$person->occupation_type === null ? 'Not Specified' : $person->occupation_type}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-5 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Institution name or Company Name</label>
                                            <input type="text" class="form-control" value="{{$person->occupation_place === null ? 'Not Specified' : $person->occupation_place}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-12 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Address</label>
                                            <input type="text" class="form-control" value="{{$person->address}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Email Address</label>
                                            <input type="text" class="form-control" value="{{$person->email}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Contact Number</label>
                                            <input type="text" class="form-control" value="{{$person->cell_number}}" id="" readonly>
                                        </div>
                                    </div>


                                    <div class="col-lg-4 col-xs-12">
                                        <div class="form-group ">
                                            <label for="">Joining date</label>
                                            <input type="text" class="form-control" value="{{$person->joining_date == null ? 'None' : $person->joining_date}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-xs-12">
                                        <div class="form-group">
                                            <label for="">Next Kin's Last Name</label>
                                            <input type="text" class="form-control" value="{{$person->nk_last_name}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-xs-12">
                                        <div class="form-group">
                                            <label for="">Next Kin's First Name</label>
                                            <input type="text" class="form-control" value="{{$person->nk_first_name}}" id="" readonly>
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-xs-12">
                                        <div class="form-group">
                                            <label for="">Next Kin's Contact Number</label>
                                            <input type="text" class="form-control" value="{{$person->nk_contact}}" id="" readonly>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            @permission('edit-finances')
                            <div class="row">
                                <h3 class="page-header text-center">Financial History</h3>

                                <div class="row">
                                    <div class="col-lg-offset-2 col-lg-9 col-xs-12">
                                        <table id="financial_history_table" class="table table-bordered">
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Date</th>
                                                <th>Amount Paid</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($person->financialHistory as $index => $finances)
                                                <tr>
                                                    <td>{{$index+1}}</td>
                                                    <td>{{$finances->payment_date}}</td>
                                                    <td>{{$finances->amount}}</td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            @endpermission
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('script')
    <script src="{{asset('/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('/plugins/datatables/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('/plugins/datatables/responsive.bootstrap.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $("span:contains('Community')").parent('a').addClass('active').click().addClass('subdrop');
            $('#financial_history_table').DataTable({
                stateSave: true,
                "ordering": false,
                language: {
                    searchPlaceholder: "Searching...."
                },
                dom: 'frtp',
                responsive: true
            });
        });
    </script>
@endsection